# Broadcasting

### 1. M1(2,4) and M2 (2,4) Broadcasting is possible
       

In [1]:
import numpy as np

arr1=np.arange(1,9).reshape(2,4)
arr2=np.arange(1,9).reshape(2,4)

print(arr1)
print()
print()
print(arr2)
print()
print()

print(arr1+arr2)


[[1 2 3 4]
 [5 6 7 8]]


[[1 2 3 4]
 [5 6 7 8]]


[[ 2  4  6  8]
 [10 12 14 16]]


### 2. M1(1,3) and M2 (4,3) Broadcasting is possible

In [2]:
import numpy as np

arr1=np.arange(1,4).reshape(1,3)
arr2=np.arange(1,13).reshape(4,3)

print(arr1)
print()
print()
print(arr2)
print()
print()

print(arr1+arr2)


[[1 2 3]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


### 3. M1(4,1) and M2 (4,3) Broadcasting is possible

In [3]:
import numpy as np

arr1=np.arange(1,5).reshape(4,1)
arr2=np.arange(1,13).reshape(4,3)

print(arr1)
print()
print()
print(arr2)
print()
print()

print(arr1+arr2)


[[1]
 [2]
 [3]
 [4]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


### 4. M1(1,3) and M2 (4,4) Broadcasting is not possible

In [4]:
import numpy as np

arr1=np.arange(1,4).reshape(1,3)
arr2=np.arange(1,17).reshape(4,4)

print(arr1)
print()
print()
print(arr2)
print()
print()

print(arr1+arr2)


[[1 2 3]]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]




ValueError: operands could not be broadcast together with shapes (1,3) (4,4) 

### 5. M1(1,3) and M2 (3,1) Broadcasting is possible

In [5]:
import numpy as np

arr1=np.arange(1,4).reshape(1,3)
arr2=np.arange(4,7).reshape(1,3)

print(arr1)
print()
print()
print(arr2)
print()
print()

print(arr1+arr2)


[[1 2 3]]


[[4 5 6]]


[[5 7 9]]


### 6. M1(1,1) and M2 (4,5) Broadcasting is possible

In [6]:

import numpy as np

arr1=np.arange(1,2).reshape(1,1)
arr2=np.arange(4,24).reshape(4,5)

print(arr1)
print()
print()
print(arr2)
print()
print()

print(arr1+arr2)


[[1]]


[[ 4  5  6  7  8]
 [ 9 10 11 12 13]
 [14 15 16 17 18]
 [19 20 21 22 23]]


[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 7. M1( , 4) and M2 (5,4) Broadcasting is possible

In [7]:

import numpy as np

arr1=np.array([1,2,3,4])
arr2=np.arange(4,24).reshape(5,4)

print(arr1)
print()
print()
print(arr2)
print()
print()

print(arr1+arr2)


[1 2 3 4]


[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


[[ 5  7  9 11]
 [ 9 11 13 15]
 [13 15 17 19]
 [17 19 21 23]
 [21 23 25 27]]
