# Fancy Indexing in numpy

### let suppose in matrix have 6 Rows and i want only 1st and 3rd one

In [1]:
import numpy as np
arr1=np.arange(1,25).reshape(6,4)

print(arr1)
print()
print()
print(arr1[[0,2]])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


[[ 1  2  3  4]
 [ 9 10 11 12]]


### now this two rows i want last two column 

In [2]:
import numpy as np
arr1=np.arange(1,25).reshape(6,4)

print(arr1)
print()
print()
print(arr1[[0,2,],2:4])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


[[ 3  4]
 [11 12]]
