# Indexing

### Single item indexing in Single Row

In [1]:
import numpy as np

arr1=np.arange(5,11)
print(arr1)

print(arr1[1])


[ 5  6  7  8  9 10]
6


### now more the 1 Rows
#### in this case if you pass only one value then in out give a Full row

In [2]:
import numpy as np

arr1=np.arange(1,25).reshape(4,6)
print(arr1)
print()
print()

print(arr1[1])


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


[ 7  8  9 10 11 12]


### single item in more then one rows

In [3]:
import numpy as np

arr1=np.arange(1,25).reshape(4,6)
print(arr1)
print()
print()

print(arr1[1,2])


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


9


### now a one Full column

In [4]:
import numpy as np

arr1=np.arange(1,25).reshape(4,6)
print(arr1)
print()
print()

print(arr1[: , 2])


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


[ 3  9 15 21]


### now two column

In [5]:

import numpy as np

arr1=np.arange(1,25).reshape(4,6)
print(arr1)
print()
print()

print(arr1[: , 2:4])


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


[[ 3  4]
 [ 9 10]
 [15 16]
 [21 22]]


# Slicing

In [6]:
import numpy as np

arr1=np.arange(1,25).reshape(4,6)
print(arr1)
print()
print()

print(arr1[ 2:4 , 4:6])


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


[[17 18]
 [23 24]]


# Iteration
### row print one by one

In [8]:
import numpy as np

arr1=np.arange(1,25).reshape(4,6)
print(arr1)
print()
print()
for i in arr1:
    print(i)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


[1 2 3 4 5 6]
[ 7  8  9 10 11 12]
[13 14 15 16 17 18]
[19 20 21 22 23 24]


### all item print one by one 

In [9]:
import numpy as np

arr1=np.arange(1,25).reshape(4,6)
print(arr1)
print()
print()
for i in np.nditer(arr1):
    print(i)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
