# Indexing with Boolean Arrat

### i have random array in which have 20 number 1 to 100 and i want only those which is >50

In [1]:
import numpy as np
arr1=np.random.randint(low=1,high=100,size=20).reshape(4,5)
print(arr1)
print()
print()
print(arr1[arr1>50])


[[59 90 48 52 46]
 [86 56 69 32 64]
 [27 37 41 91  4]
 [81 84 89 51  6]]


[59 90 52 86 56 69 64 91 81 84 89 51]


### now >50 and old number

In [2]:
import numpy as np
arr1=np.random.randint(low=1,high=100,size=20).reshape(4,5)
print(arr1)
print()
print(arr1[arr1>50])
print()
print(arr1[(arr1>50) & (arr1%2==1)])


[[73 12 63 10 18]
 [20 17 92 50 79]
 [78 39  6 51 54]
 [77 30 67  7 54]]

[73 63 92 79 78 51 54 77 67 54]

[73 63 79 51 77 67]


### now replace this old value to zero 

In [4]:
import numpy as np
arr1=np.random.randint(low=1,high=100,size=20).reshape(4,5)
print(arr1)
print()
print(arr1[arr1>50])
print()
print(arr1[(arr1>50) & (arr1%2==1)])
print()
arr1[(arr1>50) & (arr1%2==1)]=0
print()
print(arr1)


[[48  5 48 35 29]
 [82 54  4 99  3]
 [48 61  3 95 92]
 [39 86 25 21 54]]

[82 54 99 61 95 92 86 54]

[99 61 95]


[[48  5 48 35 29]
 [82 54  4  0  3]
 [48  0  3  0 92]
 [39 86 25 21 54]]
