# Numpy Operation

## Addition

In [1]:
import numpy as np

arr1=np.arange(1,11)
arr2=np.arange(11,21)
print(arr1)
print(arr2)
print()
print(arr1+arr2)



[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]

[12 14 16 18 20 22 24 26 28 30]


## Subtraction

In [2]:
import numpy as np

arr1=np.arange(1,11)
arr2=np.arange(11,21)
print(arr1)
print(arr2)
print()
print(arr2-arr1)



[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]

[10 10 10 10 10 10 10 10 10 10]


## Multiplication

In [3]:
import numpy as np

arr1=np.arange(1,11)
arr2=np.arange(11,21)
print(arr1)
print(arr2)
print()
print(arr2*arr1)



[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]

[ 11  24  39  56  75  96 119 144 171 200]


## Dot Product
### Rule if 1st Matrix column is Equal to 2nd Matrix Row then Dot Product is Possible

In [4]:
import numpy as np

arr1=np.arange(1,11).reshape(2,5)
arr2=np.arange(11,21).reshape(5,2)
print(arr1)
print(arr2)
print()
print(arr1.dot(arr2))



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]

[[245 260]
 [620 660]]


## max()

In [5]:
import numpy as np

arr2=np.arange(11,21).reshape(5,2)
print(arr2)

print()
print(arr2.max())



[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]

20


## min()

In [6]:
import numpy as np

arr2=np.arange(11,21).reshape(5,2)
print(arr2)

print()
print(arr2.min())



[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]

11


## axis=0 :
### for take full Max or min column in Matrix

In [11]:
import numpy as np

arr2=np.arange(11,21).reshape(5,2)
print(arr2)

print()
print("max column")
print(arr2.max(axis=0))
print("min column")
print(arr2.min(axis=0))



[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]

max column
[19 20]
min column
[11 12]


## axis=1 :
### for take full Max or min Row in Matrix

In [10]:
import numpy as np

arr2=np.arange(11,21).reshape(5,2)
print(arr2)

print()
print("max Row")
print(arr2.max(axis=1))
print("min Row")
print(arr2.min(axis=1))



[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]

max Row
[12 14 16 18 20]
min Row
[11 13 15 17 19]


## sum()
### all item in Matrix is add

In [9]:
import numpy as np

arr2=np.arange(11,21).reshape(2,5)
print(arr2)

print()
print(arr2.sum())





[[11 12 13 14 15]
 [16 17 18 19 20]]

155


## Column sum() : axis=0

In [12]:
import numpy as np

arr2=np.arange(11,21).reshape(2,5)
print(arr2)

print()
print(arr2.sum(axis=0))





[[11 12 13 14 15]
 [16 17 18 19 20]]

[27 29 31 33 35]


## Row sum() : axis=1

In [13]:
import numpy as np

arr2=np.arange(11,21).reshape(2,5)
print(arr2)

print()
print(arr2.sum(axis=1))





[[11 12 13 14 15]
 [16 17 18 19 20]]

[65 90]


## mean() : sum/number of item

import numpy as np

arr2=np.arange(11,21).reshape(2,5)
print(arr2)

print()
print(arr2.mean())


## std() : Standerd Deviation

In [15]:
import numpy as np

arr2=np.arange(11,21).reshape(2,5)
print(arr2)

print()
print(arr2.std())





[[11 12 13 14 15]
 [16 17 18 19 20]]

2.8722813232690143


## sin()

In [17]:
import numpy as np

arr2=np.arange(11,21).reshape(2,5)
print(arr2)

print()
print(np.sin(arr2))



[[11 12 13 14 15]
 [16 17 18 19 20]]

[[-0.99999021 -0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721  0.91294525]]


## median()

In [18]:
import numpy as np

arr2=np.arange(11,21).reshape(2,5)
print(arr2)

print()
print(np.median(arr2))



[[11 12 13 14 15]
 [16 17 18 19 20]]

15.5


### a lot of operation like log,tan,cos etc