# How to creat Numpay or n-d Array

## 1st import numpay as np 
## np.array()
### example

In [6]:
import numpy as np

arr1= np.array([1,2,3,4,5])
print(arr1)


[1 2 3 4 5]


## two row matrix 

In [7]:
import numpy as np

arr2=np.array([[1,2,3],[4,5,6]])

print(arr2)

[[1 2 3]
 [4 5 6]]


## zero matrix

In [8]:
import numpy as np

arr3=np.zeros((2,3))

print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]


## ones matrix

In [9]:
import numpy as np

arr3=np.ones((2,3))

print(arr3)

[[1. 1. 1.]
 [1. 1. 1.]]


## identity matrix

In [10]:
import numpy as np

arr3=np.identity(5)

print(arr3)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## arange like for loop range 
### examples 
### 1st 0 to 10 number print
### 2nd 5 to 15 number print
### 3rd 5 to 15 but skip 1 number

In [11]:
import numpy as np

arr3=np.arange(11)
arr4=np.arange(5,16)
arr5=np.arange(5,16,2)


print(arr3)
print(arr4)
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 5  7  9 11 13 15]


## linspace

In [12]:
import numpy as np

arr5=np.linspace(10,20,10)

print(arr5)

[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


## copy()

In [13]:
import numpy as np

arr5=np.array([1,2,3,4])

arr6=arr5.copy()
print(arr6)

[1 2 3 4]


# Properties and Attributes
## shape :
###        show number of row and columes in array

In [14]:
import numpy as np

arr5=np.array([[1,2,3,4],[6,7,8,9]])


print(arr5.shape)

(2, 4)


### 2nd example two matrix same like both have same rows and colume 

In [15]:
import numpy as np

arr5=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print (arr5)

print(" now shape of this matrix ")
print(arr5.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
 now shape of this matrix 
(2, 2, 2)


## ndim 
### number of dimension
###
###
### 1st single dimension array

In [16]:
import numpy as np

arr5=np.array([1,2,3,4])


print(arr5.ndim)

1


### 2nd two dimension array


In [17]:
import numpy as np

arr5=np.array([[1,2,3,4],[6,7,8,9]])


print(arr5.ndim)

2


### 3rd three dimension array

In [18]:
import numpy as np

arr5=np.array([[[1,2],[3,4]],[[1,2],[2,3]]])


print(arr5.ndim)

3


## size :
### number of item in array

In [19]:
import numpy as np

arr5=np.array([[[1,2],[3,4]],[[1,2],[2,3]]])


print(arr5.size)

8


## dtype :
### value data type show 

In [20]:
import numpy as np

arr5=np.array([[[1,2],[3,4]],[[1,2],[2,3]]])


print(arr5.dtype)

int32


## astype :
### change the data type like float to int 

In [21]:
import numpy as np

arr5=np.array([[[1,2],[3,4]],[[1,2],[2,3]]])


print(arr5.astype('float'))

print('now check the data type ')
print(arr5.dtype)

[[[1. 2.]
  [3. 4.]]

 [[1. 2.]
  [2. 3.]]]
now check the data type 
int32


# Random

## random.random() :
### every time give new value 

In [22]:
import numpy as np

print(np.random.random())

0.5492905151900408


## random.seed() :
### constant value 

In [23]:
import numpy as np

np.random.seed(1)
print(np.random.random())

0.417022004702574


## uniform() :
#
### i. uniform( , )

In [24]:
import numpy as np

print(np.random.uniform(1,100))

72.31212485077366


### ii. uniform( , , )

In [25]:
import numpy as np

print(np.random.uniform(1,100,20))

[ 1.01132311 30.93092469 15.52883319 10.14152088 19.43976093 35.21051198
 40.27997995 54.34285667 42.50025693 68.83673054 21.24077272 87.9336262
  3.71137173 67.37628351 42.31317543 56.31029302 14.89830692 20.61204742
 80.2737123  96.857896  ]


## Random.randint ( , ) or  ( , , )

In [26]:
import numpy as np
print(np.random.randint(1,100))
print()
print(np.random.randint(1,100,20))

64

[62 23 58  2  1 61 82  9 89 14 48 73 31 72  4 71 22 50 58  4]


## argmin()

In [29]:
import numpy as np

a=np.array([2,5,1,6,9,3,4])
print(a)
print()
print(np.argmin(a))


[2 5 1 6 9 3 4]

2


## argmax()

In [28]:
import numpy as np

a=np.array([2,5,1,6,9,3,4,8])
print(a)
print()
print(np.argmax(a))


[2 5 1 6 9 3 4 8]

4


## where( condition , Ture , fasle )
### it is use for not changes in real matrix
#
### with out where ()

In [30]:
import numpy as np

a=np.array([2,5,1,6,9,3,4])
print(a)
a[a%2==1]=-1

print(a)


[2 5 1 6 9 3 4]
[ 2 -1 -1  6 -1 -1  4]


## now where ()

In [31]:
import numpy as np

a=np.array([2,5,1,6,9,3,4])
print(a)
print(np.where(a%2==1 , -1,a))
print()

print(a)


[2 5 1 6 9 3 4]
[ 2 -1 -1  6 -1 -1  4]

[2 5 1 6 9 3 4]


## sorting

In [32]:
import numpy as np

a=np.random.randint(10,50,10)
print(a)
print()
print(np.sort(a))

[14 34 22 36 26 28 25 10 14 35]

[10 14 14 22 25 26 28 34 35 36]
