# 1 . Ravel
### it convert all matrix in single dimension

In [1]:
import numpy as np

arr2=np.arange(11,21).reshape(2,5)
print(arr2)

print()
print(arr2.ndim)

print("Ravel")
print(arr2.ravel())




[[11 12 13 14 15]
 [16 17 18 19 20]]

2
Ravel
[11 12 13 14 15 16 17 18 19 20]


# 2. Reshape

In [2]:
import numpy as np

arr2=np.arange(11,21).reshape(2,5)
print(arr2)

print()



[[11 12 13 14 15]
 [16 17 18 19 20]]



# 3. Transpose

In [5]:
import numpy as np

arr2=np.arange(11,21).reshape(2,5)
print(arr2)

print()
print(arr2.transpose())


[[11 12 13 14 15]
 [16 17 18 19 20]]

[[11 16]
 [12 17]
 [13 18]
 [14 19]
 [15 20]]


## 3.1 3D Transpose

In [6]:
import numpy as np

arr2=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr2)
print()
print("3D Transpose")
print()
print(arr2.transpose())


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

3D Transpose

[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]


# 4. Stacking
### combine two Array
#
#
## hstack : Horizontal combine

In [7]:
import numpy as np
arr1=np.arange(1,11).reshape(2,5)
arr2=np.arange(11,21).reshape(2,5)
print(arr1)
print()
print(arr2)

print()
print(np.hstack((arr1,arr2)))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[11 12 13 14 15]
 [16 17 18 19 20]]

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


## vstack : Vertical combine

In [8]:
import numpy as np
arr1=np.arange(1,11).reshape(2,5)
arr2=np.arange(11,21).reshape(2,5)
print(arr1)
print()
print(arr2)

print()
print(np.vstack((arr1,arr2)))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[11 12 13 14 15]
 [16 17 18 19 20]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# 5. Splitting

## vsplit 

In [10]:
import numpy as np
arr1=np.arange(1,11).reshape(2,5)

print(arr1)
print()
print()
print(np.vsplit(arr1,2))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]


## hsplit

In [11]:
import numpy as np
arr1=np.arange(1,25).reshape(6,4)

print(arr1)
print()
print()
print(np.hsplit(arr1,2))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])]
